### ISSUE TITLE
运行失败

### ISSUE THREAD

**Issue by SigmaLGX** [zuoqing1988/train-mtcnn-head#5]
您好，我训练P20的时候，报了这么一个错误。没搞明白

Traceback (most recent call last):
  File "/home/lgx/mtcnn_headDetection/example/train_P_net20.py", line 63, in <module>
    args.begin_epoch, args.end_epoch, args.batch_size, args.thread_num, args.frequent, args.lr, lr_epoch, args.resume)
  File "/home/lgx/mtcnn_headDetection/example/train_P_net20.py", line 15, in train_P_net20
    sym = P_Net20()
  File "/home/lgx/mtcnn_headDetection/core/symbol.py", line 54, in P_Net20
    op_type='negativemining',)
  File "<string>", line 48, in Custom
  File "/home/lgx/anaconda3/envs/sicnn/lib/python3.6/site-packages/mxnet/_ctypes/symbol.py", line 125, in _symbol_creator
    ctypes.byref(sym_handle)))
  File "/home/lgx/anaconda3/envs/sicnn/lib/python3.6/site-packages/mxnet/base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [23:48:03] src/operator/custom/custom.cc:104: Check failed: CustomOperator::Get()->Find(params.op_type) != nullptr Cannot find custom operator negativemining

Stack trace returned 10 entries:
[bt] (0) /home/lgx/anaconda3/envs/sicnn/lib/python3.6/site-packages/mxnet/libmxnet.so(dmlc::StackTrace[abi:cxx11]()+0x189) [0x7f54b2185fa9]
[bt] (1) /home/lgx/anaconda3/envs/sicnn/lib/python3.6/site-packages/mxnet/libmxnet.so(dmlc::LogMessageFatal::~LogMessageFatal()+0x3b) [0x7f54b2186a5b]
[bt] (2) /home/lgx/anaconda3/envs/sicnn/lib/python3.6/site-packages/mxnet/libmxnet.so(mxnet::op::custom::AttrParser(nnvm::NodeAttrs*)+0xf2e) [0x7f54b238ca8e]
[bt] (3) /home/lgx/anaconda3/envs/sicnn/lib/python3.6/site-packages/mxnet/libmxnet.so(nnvm::Symbol::CreateFunctor(nnvm::Op const*, std::unordered_map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >)+0x134) [0x7f54b4f138a4]
[bt] (4) /home/lgx/anaconda3/envs/sicnn/lib/python3.6/site-packages/mxnet/libmxnet.so(MXSymbolCreateAtomicSymbol+0x5f6) [0x7f54b4df0af6]
[bt] (5) /home/lgx/anaconda3/envs/sicnn/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call_unix64+0x4c) [0x7f54c2cd6ec0]
[bt] (6) /home/lgx/anaconda3/envs/sicnn/lib/python3.6/lib-dynload/../../libffi.so.6(ffi_call+0x22d) [0x7f54c2cd687d]
[bt] (7) /home/lgx/anaconda3/envs/sicnn/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(_ctypes_callproc+0x2ce) [0x7f54c2eece4e]
[bt] (8) /home/lgx/anaconda3/envs/sicnn/lib/python3.6/lib-dynload/_ctypes.cpython-36m-x86_64-linux-gnu.so(+0x13885) [0x7f54c2eed885]
[bt] (9) /home/lgx/anaconda3/envs/sicnn/bin/python(_PyObject_FastCallDict+0x8b) [0x55ba8986f5bb]

**Comment by SigmaLGX** [comment]
没事了。 搞错了，打扰。
